#!/usr/bin/env python3
"""Threshold constants for layout comparison preview layers."""

from __future__ import annotations

try:
    from scripts import layout_frequency  # type: ignore
except ImportError:
    import layout_frequency  # type: ignore


HISTOGRAM_BACKGROUND_MAX_INK = 0.018
HISTOGRAM_BACKGROUND_MIN_LIGHT = 0.96
HISTOGRAM_BACKGROUND_MAX_DARK = 0.010
HISTOGRAM_BACKGROUND_MAX_MID = 0.08

HISTOGRAM_IMAGE_MIN_INK = 0.08
HISTOGRAM_IMAGE_MIN_HIGH_SATURATION = 0.20
HISTOGRAM_IMAGE_MIN_COLOR_FRACTION = 0.55
HISTOGRAM_IMAGE_MIN_COLOR_MID = 0.20
HISTOGRAM_IMAGE_MIN_MID = 0.48
HISTOGRAM_IMAGE_MIN_ENTROPY = 0.45

HISTOGRAM_SCHEMATIC_MIN_INK = 0.020
HISTOGRAM_SCHEMATIC_MAX_DARK_LIGHT_RATIO = layout_frequency.SCHEMATIC_MAX_DARK_LIGHT_RATIO
HISTOGRAM_SCHEMATIC_MIN_LIGHT = 0.58
HISTOGRAM_SCHEMATIC_MAX_MID = 0.36

HISTOGRAM_TEXT_MIN_INK = 0.035
HISTOGRAM_TEXT_MIN_DARK_LIGHT_RATIO = layout_frequency.TEXT_MIN_DARK_LIGHT_RATIO
HISTOGRAM_TEXT_MAX_DARK_LIGHT_RATIO = layout_frequency.TEXT_MAX_DARK_LIGHT_RATIO
HISTOGRAM_TEXT_MAX_MID = layout_frequency.TEXT_MAX_LUMA_MID_FRACTION
HISTOGRAM_TEXT_MIN_BIMODAL = 0.035
HISTOGRAM_TEXT_MIN_ENTROPY = 0.32

BALANCE_BACKGROUND_MAX_INK = 0.018
BALANCE_BACKGROUND_MIN_LIGHT = 0.96
BALANCE_BACKGROUND_MAX_DARK_LIGHT_RATIO = 0.012

BALANCE_SCHEMATIC_MIN_INK = 0.020
BALANCE_SCHEMATIC_MAX_DARK_LIGHT_RATIO = 0.055
BALANCE_SCHEMATIC_MIN_LIGHT = 0.62

BALANCE_TEXT_MIN_INK = 0.035
BALANCE_TEXT_MIN_DARK_LIGHT_RATIO = 0.055
BALANCE_TEXT_MAX_DARK_LIGHT_RATIO = 0.24
BALANCE_TEXT_MAX_MID = 0.45

BALANCE_IMAGE_MIN_INK = 0.08
BALANCE_IMAGE_MIN_DARK_LIGHT_RATIO = 0.34
BALANCE_IMAGE_MIN_MID = 0.48

TILE_OVERLAY_ALPHA = 0.26
TILE_BASE_ALPHA = 1.0 - TILE_OVERLAY_ALPHA
